---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ticketingms-account
  namespace: ticketingms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ticketingms-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ticketingms_role_binding
subjects:
  - kind: ServiceAccount
    name: ticketingms-account
    namespace: ticketingms
roleRef:
  kind: ClusterRole
  name: ticketingms-role
  apiGroup: rbac.authorization.k8s.io
---

