name: deploy-auth

on:
  push:
    branches: [ "master" ]
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd auth && docker build -t zhusk12/auth .
    - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker push zhusk12/auth
    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_ACCESS_TOKEN }}
    - run: doctl kubernetes cluster kubeconfig save ticketing
    - run: kubectl rollout restart deployment auth-depl
